# Generated by Django 5.2.7 on 2025-12-12 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('external_user_email', models.CharField(blank=True, max_length=255, null=True)),
                ('external_user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to='analysis/pdf/')),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('awaiting_regions', 'Awaiting Region Selection'), ('ready_to_generate', 'Ready To Generate'), ('completed', 'Completed'), ('failed', 'Failed')], default='awaiting_regions', max_length=32)),
                ('workbook_path', models.CharField(blank=True, max_length=500, null=True)),
                ('pptx_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='analysis/pages/')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='analysis_app.analysis')),
            ],
            options={
                'ordering': ['page_number'],
                'unique_together': {('analysis', 'page_number')},
            },
        ),
        migrations.CreateModel(
            name='RegionSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(choices=[('design_data', 'Design Data'), ('bom', 'Bill Of Material'), ('slide_image', 'Slide Image')], max_length=32)),
                ('x1', models.FloatField()),
                ('y1', models.FloatField()),
                ('x2', models.FloatField()),
                ('y2', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='analysis_app.analysis')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='analysis_app.analysispage')),
            ],
            options={
                'indexes': [models.Index(fields=['analysis', 'step_type'], name='analysis_ap_analysi_b46019_idx')],
            },
        ),
    ]
