# Generated by Django 5.2.7 on 2025-12-23 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='external_user_email',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='external_user_id',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='external_user_name',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='user',
        ),
        migrations.CreateModel(
            name='ExternalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='rbi_auth', max_length=30)),
                ('external_id', models.CharField(max_length=64)),
                ('staff_id', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('role_snapshot', models.CharField(blank=True, max_length=32, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'external_id'], name='analysis_ap_provide_8b4972_idx'), models.Index(fields=['email'], name='analysis_ap_email_b70e36_idx')],
                'unique_together': {('provider', 'external_id')},
            },
        ),
        migrations.AddField(
            model_name='analysis',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='analysis_app.externaluser'),
        ),
    ]
