# analysis_app/services/ppt_builder.py

from pathlib import Path
from typing import List
from django.conf import settings
from pptx import Presentation
from pptx.util import Inches


def get_or_create_pptx(pptx_rel_path: str) -> str:
    abs_path = Path(settings.MEDIA_ROOT) / pptx_rel_path
    abs_path.parent.mkdir(parents=True, exist_ok=True)

    if not abs_path.exists():
        prs = Presentation()
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        slide.shapes.title.text = "RBI Report"
        slide.placeholders[1].text = "Generated by RBI Automation"
        prs.save(abs_path)
    return str(abs_path)


def add_images_to_presentation(pptx_abs_path: str, image_rel_paths: List[str]):
    prs = Presentation(pptx_abs_path)
    blank = prs.slide_layouts[6]

    for rel in image_rel_paths:
        img_abs = Path(settings.MEDIA_ROOT) / rel
        slide = prs.slides.add_slide(blank)
        left = Inches(0.5)
        top = Inches(0.5)
        slide.shapes.add_picture(str(img_abs), left, top, width=Inches(9))

    prs.save(pptx_abs_path)
